config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to:user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/turbo_devise_user_controller.rb
class TurboDeviseUserController < ApplicationController
 class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
          rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, 
            status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name"%>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control",placeholder:"Last Name"  %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control" ,placeholder:"Email" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control",placeholder:"Phone" %>
  </div>

  <div class="form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control",placeholder:"Twitter"  %>
  </div>
<br>
  <div >
    <%= form.submit class:"btn btn-secondary"  %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
  <td>
    <%= friend.first_name %>
  </td>

  <td>
    <%= friend.last_name %>
  </td>

  <td>
   
    <%= friend.email %>
  </td>

  <td>
    <%= friend.phone %>
  </td>

  <td>
    <%= friend.twitter %>
  </td>


  <td>
    <%= link_to "Show", friend ,  class:"btn btn-primary" %>
  </td>
  
  <td>
     <%= link_to "Edit", edit_friend_path(friend),  class:"btn btn-info"  %> 
  </td>
  <td>
      <%= button_to "Destroy", friend, method: :delete,  class:"btn btn-danger" %>
  </td>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br/>
  <%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<h1>Friend List</h1>

<div id="friends">
    <table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
          <th>First name:</th>
          <th>Last name:</th>
          <th>Email:</th>
          <th>Phone:</th>
          <th>Twitter:</th>
          <th>Show Friend:</th>
          <th>Edit Friend:</th>
          <th>Delete Friend:</th>
        </thead>
        <tbody>
  <% @friends.each do |friend| %>
    <tr>
    <%= render friend %>
    </tr>

  <% end %>
      </tbody>
      </table>
</div>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary"%>

app/views/friends/new.html.erb
<h1> ADD New friend</h1>
<br>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"><strong>Name: </strong><%= @friend.first_name %> <%= @friend.last_name %></h1>
        <p class="col-md-8 fs-4"><strong>Email: </strong><%= @friend.email %></p>
        <p class="col-md-8 fs-4"><strong>Phone: </strong><%= @friend.phone %></p>
        <p class="col-md-8 fs-4"><strong>Twitter: </strong><%= @friend.twitter %></p>
          <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary btn-lg" %> 
            <%= link_to "Back to friends", friends_path , class:"btn btn-secondary btn-lg" %>
       
      </div>
</div>
        

app/views/home/_header.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
     
        <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link"%>
   
        </li>
        <li class="nav-item">
        <%= link_to "Show friends", friends_path, class:"nav-link"%>

        </li>
         
        </li>
        <%if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Add Friend", new_friend_path, class:"nav-link"%>
        
        </li>
          <% else %>
         <li class="nav-item">
          <%= link_to "Sign In / Register", new_user_session_path, class:"nav-link"%>
  
        </li>
        <% end %>
         <%if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link"%>
    
          </li>
        
         <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
  
        </li>
         <% end %>
        
       
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us....</h1>

app/views/home/index.html.erb
<h1>Hello world!</h1>
This is my first rails webpage....

app/views/layouts/_alert.html.erb
<br>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_notice.html.erb
<br>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
     <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%=  render "home/header"%>
      <div class="container">
        <% if notice %>
          <%= render "layouts/notice"%>
        <% end %>
        <% if alert %>
          <%= render "layouts/alert"%>
        <% end %>
        <br/>
        <%= yield %>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>